export const categories = [
  { id: 'quran', name: 'Коран', icon: '📖', count: 12 },
  { id: 'tafsir', name: 'Тафсир', icon: '📝', count: 8 },
  { id: 'hadith', name: 'Хадисы', icon: '📜', count: 10 },
  { id: 'fiqh', name: 'Фикх', icon: '⚖️', count: 6 },
  { id: 'aqidah', name: 'Акида', icon: '🕌', count: 5 },
  { id: 'seerah', name: 'Сира', icon: '🌙', count: 7 },
  { id: 'lectures', name: 'Лекции', icon: '🎤', count: 15 },
  { id: 'nasheed', name: 'Нашиды', icon: '🎶', count: 20 },
  { id: 'dua', name: 'Дуа', icon: '🤲', count: 9 },
  { id: 'reminders', name: 'Напоминания', icon: '💡', count: 11 },
]

export const audioData = [
  // Quran
  { id: 1, title: 'Сура Аль-Фатиха', author: 'Шейх Судаис', duration: '3:24', icon: '📖', categoryId: 'quran', src: '' },
  { id: 2, title: 'Сура Аль-Бакара (аят 1-10)', author: 'Шейх Аш-Шурейм', duration: '4:12', icon: '📖', categoryId: 'quran', src: '' },
  { id: 3, title: 'Сура Али Имран', author: 'Шейх Микдам', duration: '15:30', icon: '📖', categoryId: 'quran', src: '' },
  { id: 4, title: 'Сура Ан-Ниса', author: 'Шейх Судаис', duration: '22:45', icon: '📖', categoryId: 'quran', src: '' },
  { id: 5, title: 'Сура Аль-Маида', author: 'Шейх Аш-Шурейм', duration: '18:20', icon: '📖', categoryId: 'quran', src: '' },
  { id: 6, title: 'Сура Аль-Кахф', author: 'Шейх Басфар', duration: '12:35', icon: '📖', categoryId: 'quran', src: '' },
  { id: 7, title: 'Сура Ясин', author: 'Шейх Судаис', duration: '4:55', icon: '📖', categoryId: 'quran', src: '' },
  { id: 8, title: 'Сура Аль-Вакиа', author: 'Шейх Микдам', duration: '6:10', icon: '📖', categoryId: 'quran', src: '' },
  { id: 9, title: 'Сура Аль-Мульк', author: 'Шейх Басфар', duration: '5:40', icon: '📖', categoryId: 'quran', src: '' },
  { id: 10, title: 'Сура Аль-Ихлас', author: 'Шейх Аш-Шурейм', duration: '1:15', icon: '📖', categoryId: 'quran', src: '' },
  { id: 11, title: 'Сура Аль-Фалах', author: 'Шейх Судаис', duration: '0:55', icon: '📖', categoryId: 'quran', src: '' },
  { id: 12, title: 'Сура Ан-Нас', author: 'Шейх Микдам', duration: '0:48', icon: '📖', categoryId: 'quran', src: '' },

  // Tafsir
  { id: 13, title: 'Тафсир суры Аль-Фатиха', author: 'Шейх Ибн Усеймин', duration: '45:20', icon: '📝', categoryId: 'tafsir', src: '' },
  { id: 14, title: 'Тафсир аята Аль-Курси', author: 'Шейх Салих аль-Фаузан', duration: '32:15', icon: '📝', categoryId: 'tafsir', src: '' },
  { id: 15, title: 'Тафсир суры Аль-Бакара (часть 1)', author: 'Ибн Таймия', duration: '55:40', icon: '📝', categoryId: 'tafsir', src: '' },
  { id: 16, title: 'Тафсир суры Аль-Бакара (часть 2)', author: 'Ибн Таймия', duration: '48:30', icon: '📝', categoryId: 'tafsir', src: '' },
  { id: 17, title: 'Тафсир суры Аль-Ихлас', author: 'Шейх Аль-Усаймин', duration: '22:10', icon: '📝', categoryId: 'tafsir', src: '' },
  { id: 18, title: 'Тафсир суры Аль-Кахф', author: 'Шейх Салих аль-Фаузан', duration: '42:55', icon: '📝', categoryId: 'tafsir', src: '' },
  { id: 19, title: 'Тафсир суры Ясин', author: 'Шейх Ибн Усеймин', duration: '28:45', icon: '📝', categoryId: 'tafsir', src: '' },
  { id: 20, title: 'Тафсир аятов о намазе', author: 'Шейх Мухаммад Салих', duration: '35:20', icon: '📝', categoryId: 'tafsir', src: '' },

  // Hadith
  { id: 21, title: '40 хадисов ан-Навави (1-10)', author: 'Шейх Ибн Усеймин', duration: '1:15:30', icon: '📜', categoryId: 'hadith', src: '' },
  { id: 22, title: '40 хадисов ан-Навави (11-20)', author: 'Шейх Ибн Усеймин', duration: '1:22:15', icon: '📜', categoryId: 'hadith', src: '' },
  { id: 23, title: '40 хадисов ан-Навави (21-30)', author: 'Шейх Ибн Усеймин', duration: '1:18:40', icon: '📜', categoryId: 'hadith', src: '' },
  { id: 24, title: '40 хадисов ан-Навави (31-40)', author: 'Шейх Ибн Усеймин', duration: '1:05:20', icon: '📜', categoryId: 'hadith', src: '' },
  { id: 25, title: 'Хадисы о намазе', author: 'Шейх аль-Альбани', duration: '45:30', icon: '📜', categoryId: 'hadith', src: '' },
  { id: 26, title: 'Хадисы о посте', author: 'Шейх Салих аль-Фаузан', duration: '38:15', icon: '📜', categoryId: 'hadith', src: '' },
  { id: 27, title: 'Хадисы о хадже', author: 'Шейх Ибн Баз', duration: '52:40', icon: '📜', categoryId: 'hadith', src: '' },
  { id: 28, title: 'Хадисы о доброте к родителям', author: 'Шейх Ибн Усеймин', duration: '28:55', icon: '📜', categoryId: 'hadith', src: '' },
  { id: 29, title: 'Хадисы о братстве', author: 'Шейх Мухаммад Салих', duration: '33:20', icon: '📜', categoryId: 'hadith', src: '' },
  { id: 30, title: 'Хадисы о покаянии', author: 'Шейх аль-Альбани', duration: '41:10', icon: '📜', categoryId: 'hadith', src: '' },

  // Fiqh
  { id: 31, title: 'Фикх намаза (часть 1)', author: 'Шейх Ибн Усеймин', duration: '1:05:30', icon: '⚖️', categoryId: 'fiqh', src: '' },
  { id: 32, title: 'Фикх намаза (часть 2)', author: 'Шейх Ибн Усеймин', duration: '58:20', icon: '⚖️', categoryId: 'fiqh', src: '' },
  { id: 33, title: 'Фикх поста в месяц Рамадан', author: 'Шейх Салих аль-Фаузан', duration: '52:45', icon: '⚖️', categoryId: 'fiqh', src: '' },
  { id: 34, title: 'Фикх закята', author: 'Шейх Ибн Баз', duration: '45:15', icon: '⚖️', categoryId: 'fiqh', src: '' },
  { id: 35, title: 'Фикх хаджа', author: 'Шейх Ибн Усеймин', duration: '1:12:40', icon: '⚖️', categoryId: 'fiqh', src: '' },
  { id: 36, title: 'Фикх торговли и сделок', author: 'Шейх Салих аль-Фаузан', duration: '38:55', icon: '⚖️', categoryId: 'fiqh', src: '' },

  // Aqidah
  { id: 37, title: 'Основы акиды (часть 1)', author: 'Шейх Ибн Усеймин', duration: '1:25:30', icon: '🕌', categoryId: 'aqidah', src: '' },
  { id: 38, title: 'Основы акиды (часть 2)', author: 'Шейх Ибн Усеймин', duration: '1:18:20', icon: '🕌', categoryId: 'aqidah', src: '' },
  { id: 39, title: 'Единобожие (Таухид)', author: 'Шейх аль-Усаймин', duration: '55:45', icon: '🕌', categoryId: 'aqidah', src: '' },
  { id: 40, title: 'Вера в Аллаха и Его имена', author: 'Шейх Ибн Баз', duration: '48:30', icon: '🕌', categoryId: 'aqidah', src: '' },
  { id: 41, title: 'Вера в ангелов', author: 'Шейх Салих аль-Фаузан', duration: '35:20', icon: '🕌', categoryId: 'aqidah', src: '' },

  // Seerah
  { id: 42, title: 'Рождение Пророка ﷺ', author: 'Шейх Ибн Усеймин', duration: '42:15', icon: '🌙', categoryId: 'seerah', src: '' },
  { id: 43, title: 'Мекканский период', author: 'Шейх Ибн Усеймин', duration: '1:05:30', icon: '🌙', categoryId: 'seerah', src: '' },
  { id: 44, title: 'Хиджра в Медину', author: 'Шейх Ибн Баз', duration: '48:20', icon: '🌙', categoryId: 'seerah', src: '' },
  { id: 45, title: 'Битва при Бадре', author: 'Шейх Салих аль-Фаузан', duration: '55:45', icon: '🌙', categoryId: 'seerah', src: '' },
  { id: 46, title: 'Завоевание Мекки', author: 'Шейх Ибн Усеймин', duration: '52:30', icon: '🌙', categoryId: 'seerah', src: '' },
  { id: 47, title: 'Последняя проповедь Пророка ﷺ', author: 'Шейх аль-Альбани', duration: '38:15', icon: '🌙', categoryId: 'seerah', src: '' },
  { id: 48, title: 'Сподвижники Пророка ﷺ', author: 'Шейх Мухаммад Салих', duration: '45:40', icon: '🌙', categoryId: 'seerah', src: '' },

  // Lectures
  { id: 49, title: 'Важность знания в Исламе', author: 'Шейх Ибн Усеймин', duration: '52:30', icon: '🎤', categoryId: 'lectures', src: '' },
  { id: 50, title: 'Как обрести покой сердца', author: 'Шейх Салих аль-Фаузан', duration: '45:15', icon: '🎤', categoryId: 'lectures', src: '' },
  { id: 51, title: 'Семья в Исламе', author: 'Шейх Ибн Баз', duration: '58:40', icon: '🎤', categoryId: 'lectures', src: '' },
  { id: 52, title: 'Достоинства мусульманина', author: 'Шейх аль-Усаймин', duration: '42:25', icon: '🎤', categoryId: 'lectures', src: '' },
  { id: 53, title: 'Опасность нововведений', author: 'Шейх Ибн Усеймин', duration: '1:05:30', icon: '🎤', categoryId: 'lectures', src: '' },
  { id: 54, title: 'Значение Сунны', author: 'Шейх аль-Альбани', duration: '48:15', icon: '🎤', categoryId: 'lectures', src: '' },
  { id: 55, title: 'Советы для молодежи', author: 'Шейх Салих аль-Фаузан', duration: '55:20', icon: '🎤', categoryId: 'lectures', src: '' },
  { id: 56, title: 'Исправление ошибок', author: 'Шейх Ибн Усеймин', duration: '42:45', icon: '🎤', categoryId: 'lectures', src: '' },
  { id: 57, title: 'Терпение в Исламе', author: 'Шейх Ибн Баз', duration: '38:30', icon: '🎤', categoryId: 'lectures', src: '' },
  { id: 58, title: 'Страх Аллаха', author: 'Шейх аль-Усаймин', duration: '45:10', icon: '🎤', categoryId: 'lectures', src: '' },
  { id: 59, title: 'О вуду', author: 'Шейх Салих аль-Фаузан', duration: '28:55', icon: '🎤', categoryId: 'lectures', src: '' },
  { id: 60, title: 'О молоке матери', author: 'Шейх Ибн Усеймин', duration: '35:20', icon: '🎤', categoryId: 'lectures', src: '' },
  { id: 61, title: 'О поклонении', author: 'Шейх Ибн Баз', duration: '52:40', icon: '🎤', categoryId: 'lectures', src: '' },
  { id: 62, title: 'О молитве', author: 'Шейх аль-Альбани', duration: '45:15', icon: '🎤', categoryId: 'lectures', src: '' },
  { id: 63, title: 'О посте', author: 'Шейх Салих аль-Фаузан', duration: '42:30', icon: '🎤', categoryId: 'lectures', src: '' },

  // Nasheed
  { id: 64, title: 'Нашед о Пророке ﷺ', author: 'Махир Зайн', duration: '4:25', icon: '🎶', categoryId: 'nasheed', src: '' },
  { id: 65, title: 'Нашед о Медине', author: 'Сами Юсуф', duration: '5:10', icon: '🎶', categoryId: 'nasheed', src: '' },
  { id: 66, title: 'Нашед о Рамадане', author: 'Махир Зайн', duration: '4:55', icon: '🎶', categoryId: 'nasheed', src: '' },
  { id: 67, title: 'Нашед о любви к Аллаху', author: 'Сами Юсуф', duration: '6:20', icon: '🎶', categoryId: 'nasheed', src: '' },
  { id: 68, title: 'Нашед о единобожии', author: 'Махир Зайн', duration: '5:35', icon: '🎶', categoryId: 'nasheed', src: '' },
  { id: 69, title: 'Нашед о Мекке', author: 'Сами Юсуф', duration: '4:45', icon: '🎶', categoryId: 'nasheed', src: '' },
  { id: 70, title: 'Нашед о покаянии', author: 'Махир Зайн', duration: '5:15', icon: '🎶', categoryId: 'nasheed', src: '' },
  { id: 71, title: 'Нашед о мире', author: 'Сами Юсуф', duration: '4:30', icon: '🎶', categoryId: 'nasheed', src: '' },
  { id: 72, title: 'Нашед о вере', author: 'Махир Зайн', duration: '5:50', icon: '🎶', categoryId: 'nasheed', src: '' },
  { id: 73, title: 'Нашед о прощении', author: 'Сами Юсуф', duration: '4:15', icon: '🎶', categoryId: 'nasheed', src: '' },
  { id: 74, title: 'Нашед о терпении', author: 'Махир Зайн', duration: '5:05', icon: '🎶', categoryId: 'nasheed', src: '' },
  { id: 75, title: 'Нашед о доброте', author: 'Сами Юсуф', duration: '4:40', icon: '🎶', categoryId: 'nasheed', src: '' },
  { id: 76, title: 'Нашед о семье', author: 'Махир Зайн', duration: '5:25', icon: '🎶', categoryId: 'nasheed', src: '' },
  { id: 77, title: 'Нашед о знании', author: 'Сами Юсуф', duration: '4:50', icon: '🎶', categoryId: 'nasheed', src: '' },
  { id: 78, title: 'Нашед о молитве', author: 'Махир Зайн', duration: '5:10', icon: '🎶', categoryId: 'nasheed', src: '' },
  { id: 79, title: 'Нашед о хадже', author: 'Сами Юсуф', duration: '4:35', icon: '🎶', categoryId: 'nasheed', src: '' },
  { id: 80, title: 'Нашед о пожилых', author: 'Махир Зайн', duration: '5:00', icon: '🎶', categoryId: 'nasheed', src: '' },
  { id: 81, title: 'Нашед о детях', author: 'Сами Юсуф', duration: '4:20', icon: '🎶', categoryId: 'nasheed', src: '' },
  { id: 82, title: 'Нашед о творении', author: 'Махир Зайн', duration: '5:45', icon: '🎶', categoryId: 'nasheed', src: '' },
  { id: 83, title: 'Нашед о Судном дне', author: 'Сами Юсуф', duration: '4:55', icon: '🎶', categoryId: 'nasheed', src: '' },

  // Dua
  { id: 84, title: 'Дуа утренняя', author: 'Шейх Ибн Усеймин', duration: '8:30', icon: '🤲', categoryId: 'dua', src: '' },
  { id: 85, title: 'Дуа вечерняя', author: 'Шейх Ибн Усеймин', duration: '7:45', icon: '🤲', categoryId: 'dua', src: '' },
  { id: 86, title: 'Дуа перед едой и после', author: 'Шейх Салих аль-Фаузан', duration: '5:20', icon: '🤲', categoryId: 'dua', src: '' },
  { id: 87, title: 'Дуа перед сном', author: 'Шейх Ибн Баз', duration: '6:15', icon: '🤲', categoryId: 'dua', src: '' },
  { id: 88, title: 'Дуа после пробуждения', author: 'Шейх аль-Усаймин', duration: '5:40', icon: '🤲', categoryId: 'dua', src: '' },
  { id: 89, title: 'Дуа на дороге', author: 'Шейх Салих аль-Фаузан', duration: '4:55', icon: '🤲', categoryId: 'dua', src: '' },
  { id: 90, title: 'Дуа в беде', author: 'Шейх Ибн Усеймин', duration: '7:25', icon: '🤲', categoryId: 'dua', src: '' },
  { id: 91, title: 'Дуа перед намазом', author: 'Шейх Ибн Баз', duration: '6:10', icon: '🤲', categoryId: 'dua', src: '' },
  { id: 92, title: 'Дуа после азана', author: 'Шейх аль-Альбани', duration: '5:35', icon: '🤲', categoryId: 'dua', src: '' },

  // Reminders
  { id: 93, title: 'Напоминание о намазе', author: 'Шейх Ибн Усеймин', duration: '15:20', icon: '💡', categoryId: 'reminders', src: '' },
  { id: 94, title: 'Напоминание о закяте', author: 'Шейх Салих аль-Фаузан', duration: '12:45', icon: '💡', categoryId: 'reminders', src: '' },
  { id: 95, title: 'Напоминание о посте', author: 'Шейх Ибн Баз', duration: '14:30', icon: '💡', categoryId: 'reminders', src: '' },
  { id: 96, title: 'Напоминание о хадже', author: 'Шейх аль-Усеймин', duration: '18:15', icon: '💡', categoryId: 'reminders', src: '' },
  { id: 97, title: 'Напоминание о доброте', author: 'Шейх Салих аль-Фаузан', duration: '16:40', icon: '💡', categoryId: 'reminders', src: '' },
  { id: 98, title: 'Напоминание о знании', author: 'Шейх Ибн Усеймин', duration: '13:25', icon: '💡', categoryId: 'reminders', src: '' },
  { id: 99, title: 'Напоминание о покаянии', author: 'Шейх Ибн Баз', duration: '15:50', icon: '💡', categoryId: 'reminders', src: '' },
  { id: 100, title: 'Напоминание о братстве', author: 'Шейх аль-Альбани', duration: '14:10', icon: '💡', categoryId: 'reminders', src: '' },
  { id: 101, title: 'Напоминание о терпении', author: 'Шейх Салих аль-Фаузан', duration: '16:35', icon: '💡', categoryId: 'reminders', src: '' },
  { id: 102, title: 'Напоминание о смирении', author: 'Шейх Ибн Усеймин', duration: '13:50', icon: '💡', categoryId: 'reminders', src: '' },
  { id: 103, title: 'Напоминание о благодарности', author: 'Шейх Ибн Баз', duration: '12:20', icon: '💡', categoryId: 'reminders', src: '' },
]
